<?php
/*
 * DeskPRO (r) has been developed by DeskPRO Ltd. https://www.deskpro.com/
 * a British company located in London, England.
 *
 * All source code and content Copyright (c) 2017, DeskPRO Ltd.
 *
 * The license agreement under which this software is released
 * can be found at https://www.deskpro.com/eula/
 *
 * By using this software, you acknowledge having read the license
 * and agree to be bound thereby.
 *
 * Please note that DeskPRO is not free software. We release the full
 * source code for our software because we trust our users to pay us for
 * the huge investment in time and energy that has gone into both creating
 * this software and supporting our customers. By providing the source code
 * we preserve our customers' ability to modify, audit and learn from our
 * work. We have been developing DeskPRO since 2001, please help us make it
 * another decade.
 *
 * Like the work you see? Think you could make it better? We are always
 * looking for great developers to join us: http://www.deskpro.com/jobs/
 *
 * ~ Thanks, Everyone at Team DeskPRO
 */

/**
 * CaptchaAntiAbuseType
 *
 * PHP version 5
 *
 * @category Class
 * @package  DeskPRO\API
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * DeskPRO API
 *
 * DeskPRO API
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace DeskPRO\API\Model;

use \ArrayAccess;
use \DeskPRO\API\ObjectSerializer;

/**
 * CaptchaAntiAbuseType Class Doc Comment
 *
 * @category Class
 * @package  DeskPRO\API
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CaptchaAntiAbuseType implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'CaptchaAntiAbuseType';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'use_recaptcha2' => 'bool',
        'recaptcha2_site_key' => 'string',
        'recaptcha2_secret_key' => 'string',
        'tickets' => 'string',
        'comments' => 'string',
        'feedback' => 'string',
        'register' => 'string',
        'sharing' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'use_recaptcha2' => null,
        'recaptcha2_site_key' => null,
        'recaptcha2_secret_key' => null,
        'tickets' => null,
        'comments' => null,
        'feedback' => null,
        'register' => null,
        'sharing' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'use_recaptcha2' => 'use_recaptcha2',
        'recaptcha2_site_key' => 'recaptcha2_site_key',
        'recaptcha2_secret_key' => 'recaptcha2_secret_key',
        'tickets' => 'tickets',
        'comments' => 'comments',
        'feedback' => 'feedback',
        'register' => 'register',
        'sharing' => 'sharing'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'use_recaptcha2' => 'setUseRecaptcha2',
        'recaptcha2_site_key' => 'setRecaptcha2SiteKey',
        'recaptcha2_secret_key' => 'setRecaptcha2SecretKey',
        'tickets' => 'setTickets',
        'comments' => 'setComments',
        'feedback' => 'setFeedback',
        'register' => 'setRegister',
        'sharing' => 'setSharing'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'use_recaptcha2' => 'getUseRecaptcha2',
        'recaptcha2_site_key' => 'getRecaptcha2SiteKey',
        'recaptcha2_secret_key' => 'getRecaptcha2SecretKey',
        'tickets' => 'getTickets',
        'comments' => 'getComments',
        'feedback' => 'getFeedback',
        'register' => 'getRegister',
        'sharing' => 'getSharing'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['use_recaptcha2'] = isset($data['use_recaptcha2']) ? $data['use_recaptcha2'] : null;
        $this->container['recaptcha2_site_key'] = isset($data['recaptcha2_site_key']) ? $data['recaptcha2_site_key'] : null;
        $this->container['recaptcha2_secret_key'] = isset($data['recaptcha2_secret_key']) ? $data['recaptcha2_secret_key'] : null;
        $this->container['tickets'] = isset($data['tickets']) ? $data['tickets'] : null;
        $this->container['comments'] = isset($data['comments']) ? $data['comments'] : null;
        $this->container['feedback'] = isset($data['feedback']) ? $data['feedback'] : null;
        $this->container['register'] = isset($data['register']) ? $data['register'] : null;
        $this->container['sharing'] = isset($data['sharing']) ? $data['sharing'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets use_recaptcha2
     *
     * @return bool
     */
    public function getUseRecaptcha2()
    {
        return $this->container['use_recaptcha2'];
    }

    /**
     * Sets use_recaptcha2
     *
     * @param bool $use_recaptcha2 use_recaptcha2
     *
     * @return $this
     */
    public function setUseRecaptcha2($use_recaptcha2)
    {
        $this->container['use_recaptcha2'] = $use_recaptcha2;

        return $this;
    }

    /**
     * Gets recaptcha2_site_key
     *
     * @return string
     */
    public function getRecaptcha2SiteKey()
    {
        return $this->container['recaptcha2_site_key'];
    }

    /**
     * Sets recaptcha2_site_key
     *
     * @param string $recaptcha2_site_key recaptcha2_site_key
     *
     * @return $this
     */
    public function setRecaptcha2SiteKey($recaptcha2_site_key)
    {
        $this->container['recaptcha2_site_key'] = $recaptcha2_site_key;

        return $this;
    }

    /**
     * Gets recaptcha2_secret_key
     *
     * @return string
     */
    public function getRecaptcha2SecretKey()
    {
        return $this->container['recaptcha2_secret_key'];
    }

    /**
     * Sets recaptcha2_secret_key
     *
     * @param string $recaptcha2_secret_key recaptcha2_secret_key
     *
     * @return $this
     */
    public function setRecaptcha2SecretKey($recaptcha2_secret_key)
    {
        $this->container['recaptcha2_secret_key'] = $recaptcha2_secret_key;

        return $this;
    }

    /**
     * Gets tickets
     *
     * @return string
     */
    public function getTickets()
    {
        return $this->container['tickets'];
    }

    /**
     * Sets tickets
     *
     * @param string $tickets tickets
     *
     * @return $this
     */
    public function setTickets($tickets)
    {
        $this->container['tickets'] = $tickets;

        return $this;
    }

    /**
     * Gets comments
     *
     * @return string
     */
    public function getComments()
    {
        return $this->container['comments'];
    }

    /**
     * Sets comments
     *
     * @param string $comments comments
     *
     * @return $this
     */
    public function setComments($comments)
    {
        $this->container['comments'] = $comments;

        return $this;
    }

    /**
     * Gets feedback
     *
     * @return string
     */
    public function getFeedback()
    {
        return $this->container['feedback'];
    }

    /**
     * Sets feedback
     *
     * @param string $feedback feedback
     *
     * @return $this
     */
    public function setFeedback($feedback)
    {
        $this->container['feedback'] = $feedback;

        return $this;
    }

    /**
     * Gets register
     *
     * @return string
     */
    public function getRegister()
    {
        return $this->container['register'];
    }

    /**
     * Sets register
     *
     * @param string $register register
     *
     * @return $this
     */
    public function setRegister($register)
    {
        $this->container['register'] = $register;

        return $this;
    }

    /**
     * Gets sharing
     *
     * @return string
     */
    public function getSharing()
    {
        return $this->container['sharing'];
    }

    /**
     * Sets sharing
     *
     * @param string $sharing sharing
     *
     * @return $this
     */
    public function setSharing($sharing)
    {
        $this->container['sharing'] = $sharing;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


