<?php
/*
 * DeskPRO (r) has been developed by DeskPRO Ltd. https://www.deskpro.com/
 * a British company located in London, England.
 *
 * All source code and content Copyright (c) 2017, DeskPRO Ltd.
 *
 * The license agreement under which this software is released
 * can be found at https://www.deskpro.com/eula/
 *
 * By using this software, you acknowledge having read the license
 * and agree to be bound thereby.
 *
 * Please note that DeskPRO is not free software. We release the full
 * source code for our software because we trust our users to pay us for
 * the huge investment in time and energy that has gone into both creating
 * this software and supporting our customers. By providing the source code
 * we preserve our customers' ability to modify, audit and learn from our
 * work. We have been developing DeskPRO since 2001, please help us make it
 * another decade.
 *
 * Like the work you see? Think you could make it better? We are always
 * looking for great developers to join us: http://www.deskpro.com/jobs/
 *
 * ~ Thanks, Everyone at Team DeskPRO
 */

/**
 * PortalAntiAbuseSettingsType
 *
 * PHP version 5
 *
 * @category Class
 * @package  DeskPRO\API
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * DeskPRO API
 *
 * DeskPRO API
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace DeskPRO\API\Model;

use \ArrayAccess;
use \DeskPRO\API\ObjectSerializer;

/**
 * PortalAntiAbuseSettingsType Class Doc Comment
 *
 * @category Class
 * @package  DeskPRO\API
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PortalAntiAbuseSettingsType implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'PortalAntiAbuseSettingsType';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'account_rate_limit' => 'object',
        'agent_rate_limit' => 'object',
        'user_rate_limit' => 'object',
        'guest_rate_limit' => 'object'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'account_rate_limit' => null,
        'agent_rate_limit' => null,
        'user_rate_limit' => null,
        'guest_rate_limit' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'account_rate_limit' => 'account_rate_limit',
        'agent_rate_limit' => 'agent_rate_limit',
        'user_rate_limit' => 'user_rate_limit',
        'guest_rate_limit' => 'guest_rate_limit'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'account_rate_limit' => 'setAccountRateLimit',
        'agent_rate_limit' => 'setAgentRateLimit',
        'user_rate_limit' => 'setUserRateLimit',
        'guest_rate_limit' => 'setGuestRateLimit'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'account_rate_limit' => 'getAccountRateLimit',
        'agent_rate_limit' => 'getAgentRateLimit',
        'user_rate_limit' => 'getUserRateLimit',
        'guest_rate_limit' => 'getGuestRateLimit'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['account_rate_limit'] = isset($data['account_rate_limit']) ? $data['account_rate_limit'] : null;
        $this->container['agent_rate_limit'] = isset($data['agent_rate_limit']) ? $data['agent_rate_limit'] : null;
        $this->container['user_rate_limit'] = isset($data['user_rate_limit']) ? $data['user_rate_limit'] : null;
        $this->container['guest_rate_limit'] = isset($data['guest_rate_limit']) ? $data['guest_rate_limit'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets account_rate_limit
     *
     * @return object
     */
    public function getAccountRateLimit()
    {
        return $this->container['account_rate_limit'];
    }

    /**
     * Sets account_rate_limit
     *
     * @param object $account_rate_limit account_rate_limit
     *
     * @return $this
     */
    public function setAccountRateLimit($account_rate_limit)
    {
        $this->container['account_rate_limit'] = $account_rate_limit;

        return $this;
    }

    /**
     * Gets agent_rate_limit
     *
     * @return object
     */
    public function getAgentRateLimit()
    {
        return $this->container['agent_rate_limit'];
    }

    /**
     * Sets agent_rate_limit
     *
     * @param object $agent_rate_limit agent_rate_limit
     *
     * @return $this
     */
    public function setAgentRateLimit($agent_rate_limit)
    {
        $this->container['agent_rate_limit'] = $agent_rate_limit;

        return $this;
    }

    /**
     * Gets user_rate_limit
     *
     * @return object
     */
    public function getUserRateLimit()
    {
        return $this->container['user_rate_limit'];
    }

    /**
     * Sets user_rate_limit
     *
     * @param object $user_rate_limit user_rate_limit
     *
     * @return $this
     */
    public function setUserRateLimit($user_rate_limit)
    {
        $this->container['user_rate_limit'] = $user_rate_limit;

        return $this;
    }

    /**
     * Gets guest_rate_limit
     *
     * @return object
     */
    public function getGuestRateLimit()
    {
        return $this->container['guest_rate_limit'];
    }

    /**
     * Sets guest_rate_limit
     *
     * @param object $guest_rate_limit guest_rate_limit
     *
     * @return $this
     */
    public function setGuestRateLimit($guest_rate_limit)
    {
        $this->container['guest_rate_limit'] = $guest_rate_limit;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


