<?php
/*
 * DeskPRO (r) has been developed by DeskPRO Ltd. https://www.deskpro.com/
 * a British company located in London, England.
 *
 * All source code and content Copyright (c) 2017, DeskPRO Ltd.
 *
 * The license agreement under which this software is released
 * can be found at https://www.deskpro.com/eula/
 *
 * By using this software, you acknowledge having read the license
 * and agree to be bound thereby.
 *
 * Please note that DeskPRO is not free software. We release the full
 * source code for our software because we trust our users to pay us for
 * the huge investment in time and energy that has gone into both creating
 * this software and supporting our customers. By providing the source code
 * we preserve our customers' ability to modify, audit and learn from our
 * work. We have been developing DeskPRO since 2001, please help us make it
 * another decade.
 *
 * Like the work you see? Think you could make it better? We are always
 * looking for great developers to join us: http://www.deskpro.com/jobs/
 *
 * ~ Thanks, Everyone at Team DeskPRO
 */

/**
 * SnippetType
 *
 * PHP version 5
 *
 * @category Class
 * @package  DeskPRO\API
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * DeskPRO API
 *
 * DeskPRO API
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace DeskPRO\API\Model;

use \ArrayAccess;
use \DeskPRO\API\ObjectSerializer;

/**
 * SnippetType Class Doc Comment
 *
 * @category Class
 * @package  DeskPRO\API
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SnippetType implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'SnippetType';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'person' => 'object',
        'title' => 'string',
        'labels' => 'string[]',
        'types' => 'string[]',
        'translations' => 'object[]',
        'shortcut_code' => 'string',
        'is_draft' => 'bool',
        'is_split' => 'bool',
        'is_ownership_global' => 'bool',
        'is_visible_global' => 'bool',
        'ownership_teams' => 'string[]',
        'visible_departments' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'person' => null,
        'title' => null,
        'labels' => null,
        'types' => null,
        'translations' => null,
        'shortcut_code' => null,
        'is_draft' => null,
        'is_split' => null,
        'is_ownership_global' => null,
        'is_visible_global' => null,
        'ownership_teams' => null,
        'visible_departments' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'person' => 'person',
        'title' => 'title',
        'labels' => 'labels',
        'types' => 'types',
        'translations' => 'translations',
        'shortcut_code' => 'shortcut_code',
        'is_draft' => 'is_draft',
        'is_split' => 'is_split',
        'is_ownership_global' => 'is_ownership_global',
        'is_visible_global' => 'is_visible_global',
        'ownership_teams' => 'ownership_teams',
        'visible_departments' => 'visible_departments'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'person' => 'setPerson',
        'title' => 'setTitle',
        'labels' => 'setLabels',
        'types' => 'setTypes',
        'translations' => 'setTranslations',
        'shortcut_code' => 'setShortcutCode',
        'is_draft' => 'setIsDraft',
        'is_split' => 'setIsSplit',
        'is_ownership_global' => 'setIsOwnershipGlobal',
        'is_visible_global' => 'setIsVisibleGlobal',
        'ownership_teams' => 'setOwnershipTeams',
        'visible_departments' => 'setVisibleDepartments'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'person' => 'getPerson',
        'title' => 'getTitle',
        'labels' => 'getLabels',
        'types' => 'getTypes',
        'translations' => 'getTranslations',
        'shortcut_code' => 'getShortcutCode',
        'is_draft' => 'getIsDraft',
        'is_split' => 'getIsSplit',
        'is_ownership_global' => 'getIsOwnershipGlobal',
        'is_visible_global' => 'getIsVisibleGlobal',
        'ownership_teams' => 'getOwnershipTeams',
        'visible_departments' => 'getVisibleDepartments'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['person'] = isset($data['person']) ? $data['person'] : null;
        $this->container['title'] = isset($data['title']) ? $data['title'] : null;
        $this->container['labels'] = isset($data['labels']) ? $data['labels'] : null;
        $this->container['types'] = isset($data['types']) ? $data['types'] : null;
        $this->container['translations'] = isset($data['translations']) ? $data['translations'] : null;
        $this->container['shortcut_code'] = isset($data['shortcut_code']) ? $data['shortcut_code'] : null;
        $this->container['is_draft'] = isset($data['is_draft']) ? $data['is_draft'] : null;
        $this->container['is_split'] = isset($data['is_split']) ? $data['is_split'] : null;
        $this->container['is_ownership_global'] = isset($data['is_ownership_global']) ? $data['is_ownership_global'] : null;
        $this->container['is_visible_global'] = isset($data['is_visible_global']) ? $data['is_visible_global'] : null;
        $this->container['ownership_teams'] = isset($data['ownership_teams']) ? $data['ownership_teams'] : null;
        $this->container['visible_departments'] = isset($data['visible_departments']) ? $data['visible_departments'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets person
     *
     * @return object
     */
    public function getPerson()
    {
        return $this->container['person'];
    }

    /**
     * Sets person
     *
     * @param object $person person
     *
     * @return $this
     */
    public function setPerson($person)
    {
        $this->container['person'] = $person;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string $title title
     *
     * @return $this
     */
    public function setTitle($title)
    {
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets labels
     *
     * @return string[]
     */
    public function getLabels()
    {
        return $this->container['labels'];
    }

    /**
     * Sets labels
     *
     * @param string[] $labels labels
     *
     * @return $this
     */
    public function setLabels($labels)
    {
        $this->container['labels'] = $labels;

        return $this;
    }

    /**
     * Gets types
     *
     * @return string[]
     */
    public function getTypes()
    {
        return $this->container['types'];
    }

    /**
     * Sets types
     *
     * @param string[] $types types
     *
     * @return $this
     */
    public function setTypes($types)
    {
        $this->container['types'] = $types;

        return $this;
    }

    /**
     * Gets translations
     *
     * @return object[]
     */
    public function getTranslations()
    {
        return $this->container['translations'];
    }

    /**
     * Sets translations
     *
     * @param object[] $translations translations
     *
     * @return $this
     */
    public function setTranslations($translations)
    {
        $this->container['translations'] = $translations;

        return $this;
    }

    /**
     * Gets shortcut_code
     *
     * @return string
     */
    public function getShortcutCode()
    {
        return $this->container['shortcut_code'];
    }

    /**
     * Sets shortcut_code
     *
     * @param string $shortcut_code shortcut_code
     *
     * @return $this
     */
    public function setShortcutCode($shortcut_code)
    {
        $this->container['shortcut_code'] = $shortcut_code;

        return $this;
    }

    /**
     * Gets is_draft
     *
     * @return bool
     */
    public function getIsDraft()
    {
        return $this->container['is_draft'];
    }

    /**
     * Sets is_draft
     *
     * @param bool $is_draft is_draft
     *
     * @return $this
     */
    public function setIsDraft($is_draft)
    {
        $this->container['is_draft'] = $is_draft;

        return $this;
    }

    /**
     * Gets is_split
     *
     * @return bool
     */
    public function getIsSplit()
    {
        return $this->container['is_split'];
    }

    /**
     * Sets is_split
     *
     * @param bool $is_split is_split
     *
     * @return $this
     */
    public function setIsSplit($is_split)
    {
        $this->container['is_split'] = $is_split;

        return $this;
    }

    /**
     * Gets is_ownership_global
     *
     * @return bool
     */
    public function getIsOwnershipGlobal()
    {
        return $this->container['is_ownership_global'];
    }

    /**
     * Sets is_ownership_global
     *
     * @param bool $is_ownership_global is_ownership_global
     *
     * @return $this
     */
    public function setIsOwnershipGlobal($is_ownership_global)
    {
        $this->container['is_ownership_global'] = $is_ownership_global;

        return $this;
    }

    /**
     * Gets is_visible_global
     *
     * @return bool
     */
    public function getIsVisibleGlobal()
    {
        return $this->container['is_visible_global'];
    }

    /**
     * Sets is_visible_global
     *
     * @param bool $is_visible_global is_visible_global
     *
     * @return $this
     */
    public function setIsVisibleGlobal($is_visible_global)
    {
        $this->container['is_visible_global'] = $is_visible_global;

        return $this;
    }

    /**
     * Gets ownership_teams
     *
     * @return string[]
     */
    public function getOwnershipTeams()
    {
        return $this->container['ownership_teams'];
    }

    /**
     * Sets ownership_teams
     *
     * @param string[] $ownership_teams ownership_teams
     *
     * @return $this
     */
    public function setOwnershipTeams($ownership_teams)
    {
        $this->container['ownership_teams'] = $ownership_teams;

        return $this;
    }

    /**
     * Gets visible_departments
     *
     * @return string[]
     */
    public function getVisibleDepartments()
    {
        return $this->container['visible_departments'];
    }

    /**
     * Sets visible_departments
     *
     * @param string[] $visible_departments visible_departments
     *
     * @return $this
     */
    public function setVisibleDepartments($visible_departments)
    {
        $this->container['visible_departments'] = $visible_departments;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


