<?php
/*
 * DeskPRO (r) has been developed by DeskPRO Ltd. https://www.deskpro.com/
 * a British company located in London, England.
 *
 * All source code and content Copyright (c) 2017, DeskPRO Ltd.
 *
 * The license agreement under which this software is released
 * can be found at https://www.deskpro.com/eula/
 *
 * By using this software, you acknowledge having read the license
 * and agree to be bound thereby.
 *
 * Please note that DeskPRO is not free software. We release the full
 * source code for our software because we trust our users to pay us for
 * the huge investment in time and energy that has gone into both creating
 * this software and supporting our customers. By providing the source code
 * we preserve our customers' ability to modify, audit and learn from our
 * work. We have been developing DeskPRO since 2001, please help us make it
 * another decade.
 *
 * Like the work you see? Think you could make it better? We are always
 * looking for great developers to join us: http://www.deskpro.com/jobs/
 *
 * ~ Thanks, Everyone at Team DeskPRO
 */

/**
 * CaptchaAntiAbuseTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  DeskPRO\API
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * DeskPRO API
 *
 * DeskPRO API
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace DeskPRO\API;

/**
 * CaptchaAntiAbuseTypeTest Class Doc Comment
 *
 * @category    Class */
// * @description CaptchaAntiAbuseType
/**
 * @package     DeskPRO\API
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CaptchaAntiAbuseTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CaptchaAntiAbuseType"
     */
    public function testCaptchaAntiAbuseType()
    {
    }

    /**
     * Test attribute "use_recaptcha2"
     */
    public function testPropertyUseRecaptcha2()
    {
    }

    /**
     * Test attribute "recaptcha2_site_key"
     */
    public function testPropertyRecaptcha2SiteKey()
    {
    }

    /**
     * Test attribute "recaptcha2_secret_key"
     */
    public function testPropertyRecaptcha2SecretKey()
    {
    }

    /**
     * Test attribute "tickets"
     */
    public function testPropertyTickets()
    {
    }

    /**
     * Test attribute "comments"
     */
    public function testPropertyComments()
    {
    }

    /**
     * Test attribute "feedback"
     */
    public function testPropertyFeedback()
    {
    }

    /**
     * Test attribute "register"
     */
    public function testPropertyRegister()
    {
    }

    /**
     * Test attribute "sharing"
     */
    public function testPropertySharing()
    {
    }
}
