<?php
/*
 * DeskPRO (r) has been developed by DeskPRO Ltd. https://www.deskpro.com/
 * a British company located in London, England.
 *
 * All source code and content Copyright (c) 2017, DeskPRO Ltd.
 *
 * The license agreement under which this software is released
 * can be found at https://www.deskpro.com/eula/
 *
 * By using this software, you acknowledge having read the license
 * and agree to be bound thereby.
 *
 * Please note that DeskPRO is not free software. We release the full
 * source code for our software because we trust our users to pay us for
 * the huge investment in time and energy that has gone into both creating
 * this software and supporting our customers. By providing the source code
 * we preserve our customers' ability to modify, audit and learn from our
 * work. We have been developing DeskPRO since 2001, please help us make it
 * another decade.
 *
 * Like the work you see? Think you could make it better? We are always
 * looking for great developers to join us: http://www.deskpro.com/jobs/
 *
 * ~ Thanks, Everyone at Team DeskPRO
 */

/**
 * AgentsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  DeskPRO\API
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * DeskPRO API
 *
 * DeskPRO API
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace DeskPRO\API;

use \DeskPRO\API\Configuration;
use \DeskPRO\API\ApiException;
use \DeskPRO\API\ObjectSerializer;

/**
 * AgentsApiTest Class Doc Comment
 *
 * @category Class
 * @package  DeskPRO\API
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AgentsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteAgentById
     *
     * .
     *
     */
    public function testDeleteAgentById()
    {
    }

    /**
     * Test case for deleteAgentByIdAgentPermission
     *
     * .
     *
     */
    public function testDeleteAgentByIdAgentPermission()
    {
    }

    /**
     * Test case for deleteAgentTeamById
     *
     * .
     *
     */
    public function testDeleteAgentTeamById()
    {
    }

    /**
     * Test case for getAgentAssignedToChat
     *
     * .
     *
     */
    public function testGetAgentAssignedToChat()
    {
    }

    /**
     * Test case for getAgentById
     *
     * .
     *
     */
    public function testGetAgentById()
    {
    }

    /**
     * Test case for getAgentCount
     *
     * .
     *
     */
    public function testGetAgentCount()
    {
    }

    /**
     * Test case for getAgentGroupById
     *
     * .
     *
     */
    public function testGetAgentGroupById()
    {
    }

    /**
     * Test case for getAgentGroupCount
     *
     * .
     *
     */
    public function testGetAgentGroupCount()
    {
    }

    /**
     * Test case for getAgentGroups
     *
     * .
     *
     */
    public function testGetAgentGroups()
    {
    }

    /**
     * Test case for getAgentOnline
     *
     * .
     *
     */
    public function testGetAgentOnline()
    {
    }

    /**
     * Test case for getAgentTeamById
     *
     * .
     *
     */
    public function testGetAgentTeamById()
    {
    }

    /**
     * Test case for getAgentTeamByIdAgent
     *
     * .
     *
     */
    public function testGetAgentTeamByIdAgent()
    {
    }

    /**
     * Test case for getAgentTeamCount
     *
     * .
     *
     */
    public function testGetAgentTeamCount()
    {
    }

    /**
     * Test case for getAgentTeams
     *
     * .
     *
     */
    public function testGetAgentTeams()
    {
    }

    /**
     * Test case for getAgents
     *
     * .
     *
     */
    public function testGetAgents()
    {
    }
}
